use_frameworks!
platform :ios, '9.0'


target 'Demo' do

  pod 'JacKit',        :path => '../../JacKit/'
  pod 'MudoxKit/All',  :path => '../'

  pod 'Eureka'

  target 'Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
