use_frameworks!
platform :ios, '9.0'

inhibit_all_warnings!

target 'Demo' do

  # Travis-CI set `CI` on macOS environment
  if ENV['CI'] == 'true'
    pod 'JacKit',  :git  => 'https://github.com/mudox/jac-kit.git'
  else
    pod 'JacKit',  :path => '/Users/mudox/Develop/Apple/Frameworks/JacKit'
  end

  pod 'MudoxKit/All',  :path => '../'

  pod 'Eureka'

  target 'Test' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'

    pod 'RxTest'
    pod 'RxBlocking'
    pod 'RxNimble'
  end

end
